FROM payara/micro

ARG WAR_FILE=payara-showcase.war

COPY target/$WAR_FILE $DEPLOY_DIR

HEALTHCHECK --start-period=10s --timeout=60s --retries=10 --interval=5s CMD curl -f http://localhost:9990/health/ready || exit 1

ENV JAVA_OPTS="-Djboss.server.default.config=standalone-microprofile.xml"

CMD ["--deploymentDir", "/opt/payara/deployments", "--contextroot", "/"]